config/routes.rb
WarmGreet::Application.routes.draw do

  get "guideline/index"

  get "about/index"

  get "electronics/index"

  get "writestory/write"

  get "profile/show"

  get "thankyou/index"

  get "sessions/new"

  get "merchants/index"

  get "reviews/story"

  get "favorites/show"

  get "follows/following"


  get "follows/followers"

  resources :users, :only => [:create, :new, :show, :edit, :update, :index, :profile] do
    resources :follows, :only => [:create, :destroy]
    get 'activate'
  end

  resources :categories, :only => [:create, :new, :show, :edit, :update, :index, :profile] do
    resources :follows, :only => [:create, :destroy]
    get 'activate'
  end

  


  resources :customers, :only => [:create, :new, :show, :edit, :update, :index] do
    #resources :follows, :only => [:create, :destroy]
    get 'activate'
  end

  resource :session, :only => [:create, :destroy, :new]

  resource :customersession, :only => [:create, :destroy, :new]

  resources :restaurants, :except => [:index, :new, :create] do
    resources :reviews, :only => [:create, :new, :index]
    resources :favorites, :only => [:create, :destroy]
  end

  resources :merchants, :except => [:index, :new, :create] do
    resources :reviews, :only => [:create, :new, :index]
    resources :favorites, :only => [:create, :destroy]
  end

  get 'search' => "merchants#search"

  #resources :cities, :only => [:show, :index] do
   # resources :restaurants, :only => [:index, :new, :create]
  #end

  resources :countries, :only => [:show, :index] do
    resources :merchants, :only => [:index, :new, :create]
  end

  resources :reviews, :only => [:show, :edit, :update, :destroy] do
    resources :vote_tags, :only => [:create, :destroy]
  end

  get '/auth/:provider/callback', to: 'sessions#create'

  root :to => "merchants#index"
  end

app/models/merchant.rb
class Merchant < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, :use => :slugged

  attr_accessible :name, :username, :password, :email, :website, :phone, :country_id, :category_ids, :photo, :avg_rtg
  attr_reader :password

  
  validates :name, :country_id, presence: true

  validates :name, uniqueness: {:scope => :website, :message => "Merchant already exists!"}

  has_attached_file :photo, :styles => {
    :big => "250x250>",
    :medium => "100x100#",
    :small => "60x60#"
  }

  #include RankedModel
    #ranks :row_order

  paginates_per 5

  include PgSearch
    multisearchable :against => [:name]

  has_one :customer

  has_many :tags

  has_many :categories,
  through: :tags,
  source: :category,
  dependent: :destroy

  has_many :reviews,
  dependent: :destroy

  has_many :reviewers,
  through: :reviews,
  source: :user

  belongs_to :country

  has_many :favorites,
  dependent: :destroy

  has_many :users_who_favorited,
  through: :favorites,
  source: :user

  after_create do
    avg_rtg = average_rating
  end

  def average_rating
    total = 0
    count = self.reviews.count

    if count == 0
      return 0
    else
      self.reviews.each do |review|
        total += review.rating
      end

      avg_rtg = (total.to_f / count).round(1)
      return avg_rtg
    end
  end
  

  def ranking(merchant)
    #@merchants.each_with_index do |merchant, i|
    @country = Country.find(1)
    @merchants = @country.merchants.select("merchants.*, AVG(reviews.rating) AS avg_rating")
                        .joins("LEFT JOIN reviews ON reviews.merchant_id = merchants.id")
                        .group("merchants.id")
                        .order("avg_rating DESC NULLS LAST")
                        
    
    @merchants.each_with_index do |m, i|
      if m.id == merchant.id
        @result = i + 1
      end
    end 

    return @result
    #return @merchants.count(:conditions => ['avg_rating > ?', self.avg_rtg])
    
  end

   def self.find_by_credentials(username, password)
    merchant = (Merchant.find_by_username(username) || Merchant.find_by_email(username))
    merchant.try(:is_password?, password) ? merchant : nil
  end


end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  before_filter :require_signed_in!, :only => [:new]

  def new
    @country = Country.find(params[:country_id])
    @merchant = @country.merchants.new
  end

  def create
    @country = Country.find(params[:country_id])
    @merchant = @country.merchants.new(params[:merchant])

    if @merchant.save
      redirect_to merchant_url(@merchant)
    else
      render :json => @merchant.errors.full_messages
    end
  end

  def edit
    @merchant = Merchant.find(params[:id])
  end

  def update
    @merchant = Merchant.find(params[:id])

    if @merchant.update_attributes(params[:merchant])
      redirect_to merchant_url(@merchant)
    else
      render :json => @merchant.errors.full_messages
    end
  end

  def show
    @merchant = Merchant.find(params[:id])
    #puts '#' * 2000
    #puts @merchant.nil?
    # puts current_user.favorite_places.empty?
    #@fav = Favorite.find_by_user_id(current_user.id)
    #puts @fav.empty?
    # merchant.includes(:reviews, :categories, :city, :state, :users_who_favorited).find(params[:id])
  end

  def index
    #@country = Country.find(params[:country_id])
    @country = Country.find(1)

    @category = Category.all

    @merchants = @country.merchants.select("merchants.*, AVG(reviews.rating) AS avg_rating")
                        .joins("LEFT JOIN reviews ON reviews.merchant_id = merchants.id")
                        .group("merchants.id")
                        .order("avg_rating DESC NULLS LAST")
                        .page(params[:page])
                        .per(5)

    @reviews = Review.select("reviews.*")
                     .joins("JOIN merchants ON reviews.merchant_id = merchants.id")
                     .joins("JOIN countries ON countries.id = merchants.country_id")
                     .where("countries.id = ?", @country.id)
                     .group("reviews.id")
                     .order("reviews.created_at")
                     .last(5)
                     .reverse!
  end

  def destroy
    @merchant = merchant.find(params[:id])

    @merchant.destroy

    redirect_to merchants_url
  end

  def search
    @country = Country.find(1)
    @results = PgSearch.multisearch(params[:query])

    if @results.empty?
      return []
    elsif Category.all.include?(@results.first.searchable)
      @category = @results.first.searchable
        .merchants.where("country_id = 1")
        .sort!{ |a, b| a.average_rating <=> b.average_rating }
        .reverse!

      @merchants = Kaminari.paginate_array(@category)
                             .page(params[:page])
                             .per(10)
    else
      @merchants = @results.map(&:searchable).sort!{ |a, b| a.average_rating <=> b.average_rating }.reverse!

      @merchants = Kaminari.paginate_array(@merchants).page(params[:page]).per(10)
    end

    # @merchants = merchant.includes(:categories).where("city_id = ? AND categories.id = ?", params[:city_id], params[:cat_id]).page(params[:page])
  end

end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/views/merchants/_content.html.erb
 <div class="root-content-container">

  <div class="row">
    <div class = "content-main-header-root col-md-7">
        <strong class="category-separator-root">Discover what shoppers say about their online experience</strong>    
    </div>
    
    <div class="col-md-5">
      <hr class="category-name-separator">
    </div>
  </div>

<% category.feeds.sort_by{ |rev| rev.created_at }.reverse!.each_with_index do |review, i| %>

 


  
    <div style="display:inline-block">
        
        <a href="<%=merchant_url(review.merchant)%>" style="z-index:99;">
          <% if review.merchant.photo.file? %>
          <%= image_tag review.merchant.photo.url(:big), size: "100x100" %>
          <% else %>
            <%= image_tag "WGSlice/default-merchant.png", size: "100x100" %>
          <% end %>
        </a>
      

      
        

       

          <span class="attribute-container">

            <span><%= link_to review.user.username, user_url(review.user), :class => "story-writer" %>
            </span>

            <br>
            <%= image_tag("WGSlice/WGv5-icon_story.png", :class => "story-badge-in-profile") %>

            <span class="story-badge-in-profile-text"><%= review.user.reviews.count %> stories</span> 
            <%= image_tag("WGSlice/WGv5-icon_thumbs.png", :class => "thumbs-badge-in-profile") %>

            <span class="thumbs-badge-in-profile-text"> <%= review.user.count_thumbs_up%> thumbs</span>
            
            
            
          </span>
      </div>

      <div class="review-body">
            <h3 class="story-title">"<%= review.title %>"</h3>
            
            <span>Rating: <%= review.rating %> - 
            <% if review.created_at > Time.now.beginning_of_day %>
                  <%="Written #{time_ago_in_words(review.created_at)} ago"%>
              <% else %>
                  Written on <%= review.created_at.strftime("%m/%d/%Y") %>
              <% end %>
            </span>
            <br><br>
          <%= raw review.body %>

        
          <br>
        

          <div>
            <br>
          <% if review.vote_tags.empty? %>
              <span class="badge-feed">0</span>
            
            <% else %>
            
              <span class="badge-feed"><%= review.vote_tags.count %></span>
              
            
            <% end %>
          </div>

          <% if signed_in? %>
            <% unless current_user == review.user %>
              <% if !current_user.voted_reviews.include?(review) %>
                <%= link_to image_tag("WGSlice/helpfull-btn.png", class:"helpful-btn" ), review_vote_tags_url(review), method: :post, form_class: "cool-button"%>
              <% else %>
                <%= image_tag("WGSlice/helpfull-btn.png", class:"helpful-btn-active") %>
              <% end %>
            <% else %>
          <% end %>

           
            
          <% end %>
      
         </div>
      <hr>

<% end %>

</div>

      

app/views/merchants/_form.html.erb
<% action = (merchant.persisted? ? merchant_url(merchant) : country_merchants_url) %>
<% method = (merchant.persisted? ? "put" : "post") %>
<% message = (merchant.persisted? ? "Update merchant" : "Add New Merchant") %>


<form class="form-signin" role="form" action="<%= action %>"  method="post" enctype="multipart/form-data">
  <input
       name="authenticity_token"
       type="hidden"
       value="<%= form_authenticity_token %>">

  <h2 class="form-signin-heading"><%= message %></h2>
  <p class="lead">Jadilah yang pertama dalam menceritakan merchant ini</p>

  <input type="text" class="form-control" placeholder="Merchant's name" name="merchant[name]" required="" autofocus="">
  <br>
  <input type="url" class="form-control" placeholder="Awali dengan http://" name="merchant[website]" required="">

  <% Category.all.each do |category| %>
  <label class="checkbox">
    <input type="checkbox" value="<%= category.id %>"> <%= category.name %>
  </label>
  <% end %>
      <input type="hidden" name="merchant[category_ids][]" value="">

  <select
         class="textbdox-merchant-country"
         name="merchant[country_id]">
         <% Country.all.each do |country| %>
          <option><%= country.name %></option>
         <% end %>
      </select>
  <br><br>

  <button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>
</form>

app/views/merchants/content_ideal.html.erb
<% category.merchants.first(1).each_with_index do |merchant, i| %>

<div class = "content-main-header">
  
    
      <strong class="category-separator"><%= category.name.capitalize %> </strong> 
      
      <hr class="separator-pic">
</div>

 <div class="prof-review-in-index group">
  <div class="row">
     <div class="prof-left-index group col-md-6"> 
      

        <% if merchant.reviews.first %>
          <a href="<%= merchant_url(merchant) %>">
            <% if merchant.photo.file? %>
              <%= image_tag merchant.photo.url(:small) %>
            <% else %>
              <%= image_tag "WGSlice/default-merchant-banner.png", class:"default-merchant-banner-category" %>
            <% end %>
    
          </a>
                     
          <br>
        
         
            <strong style="position:absolute; width:98%; font-style: italic; font-family:'Bariol'; font-size:1.5em; font-weight:bold; margin-left:25%; margin-top:5%">
              "<%= merchant.reviews.first.title %>"
            </strong>

            
         



            <strong style="position:absolute; width:100%; font-family:'Bariol'; font-size:1em; font-weight:bold; margin-left:25%; margin-top:21%;">
              - <%= merchant.reviews.first.user.username %> shopping story <br> (<% if merchant.reviews.first.created_at > Time.now.beginning_of_day %>
              <%="#{time_ago_in_words(merchant.reviews.first.created_at)} ago"%>
              <br>
          <% else %>
              <%= merchant.reviews.first.created_at.strftime("%m/%d/%Y") %>
          <% end %>)
            </strong>

            <br> <br>

             <strong class="story-icon-index"><%= image_tag("WGSlice/WGv5-icon_story.png", :class => "story-badge") %></strong>

          <strong class="story-icon-index-text"><%= merchant.reviews.first.user.reviews.count %> Stories</strong> 


        
        <strong class="story-thumb-index"><%= image_tag("WGSlice/WGv5-icon_thumbs.png", :class => "story-badge") %></strong>

         <strong class="story-thumb-index-text"> <%= merchant.reviews.first.user.count_thumbs_up%> thumbs</strong>
          
          
          

        
          <% if merchant.reviews.first.user.photo.file? %>
            <%= image_tag merchant.reviews.first.user.photo.url(:big) %>
            <% elsif merchant.reviews.first.user.image? %>
              <%= image_tag merchant.reviews.first.user.image, size: "80x80" %>
            <% else %>
              <% if merchant.reviews.first.user.gender=="M" %>
                <%= image_tag "WGSlice/default-user-male.png", class:"review-pic-index" %>
              <% elsif merchant.reviews.first.user.gender=="F" %>
                <%= image_tag "WGSlice/default-user-female.png", class:"review-pic-index" %>
              <% else %>
                <%= image_tag "WGSlice/default-user-male.png", class:"review-pic-index" %>
              <% end %>
            <% end %>
          

            
            <strong class="review-body-index">
              <%= merchant.reviews.first.body %>
              <br><br>
              See more shopping experience on <br>
              <div class="button-writing-index-bg">
                <span>
                 <%= link_to merchant.name, merchant_url(merchant) %>
               </span>
              </div>
            </strong>
               
            <hr class = "review-body-index-separator">
          <%  end %>
        </div>

        <div class="prof-right-index col-md-6">
                      <% category.merchants.sample(2).each_with_index do |merchantright, i| %>
                        
                       <a href="<%= merchant_url(merchantright) %>">
                          <% if merchantright.photo.file? %>
                            <%= image_tag merchantright.photo.url(:big) %>
                          <% else %>
                            <%= image_tag "WGSlice/default-merchant.png", class:"default-merchant-picture-category"  %>
                          <% end %>
                       </a>



                         <% if merchantright.reviews.first %>

                          <div class="prof-right-rating">
                              Rating: <%= merchantright.reviews.first.rating %>
                          </div>

                          <strong class="prof-right-index-title">
                              "<%= merchantright.reviews.first.title %>"
                              <br>
                              - <% if merchantright.reviews.first.created_at > Time.now.beginning_of_day %>
                              <%="- #{time_ago_in_words(merchant.reviews.first.created_at)} ago"%>
                            <br>
                            <% else %>
                              <%= merchantright.reviews.first.created_at.strftime("%m/%d/%Y") %>
                            <% end %>
                          </strong>

                          <br>
                     



                          <strong class="prof-right-name">
                            <%= merchantright.reviews.first.user.username%>
                          </strong>

                          <br>

                          
                          <strong class="review-body-index-right">
                            <%#= merchant.reviews.first.body %>
                            
                            More shopping story on <br>
                            <div class="button-writing-index-bg">
                              <span>
                               <%= link_to merchantright.name, merchant_url(merchantright) %>
                              </span>
                            </div>
                          </strong>
                      
                      
                      
                          <div class = "merchant-right-pic">
                            <% if merchantright.reviews.first.user.photo.file? %>
                              <%= image_tag merchantright.reviews.first.user.photo.url(:big) %>
                            <% elsif merchantright.reviews.first.user.image? %>
                             <%= image_tag merchantright.reviews.first.user.image, size: "80x80" %>
                            <% else %>
                                <% if merchantright.reviews.first.user.gender=="M" %>
                                  <%= image_tag "WGSlice/default-user-male.png", size: "80x80", class:"prof-right-review-pic" %>
                                <% elsif merchantright.reviews.first.user.gender=="F" %>
                                  <%= image_tag "WGSlice/default-user-female.png", size: "80x80", class:"prof-right-review-pic" %>
                                <% else %>
                                  <%= image_tag "WGSlice/default-user-male.png", size: "80x80", class:"prof-right-review-pic" %>
                                <% end %>
                            <% end %>
                          </div>
                        

                       
                        <% else %>
                          <strong class="prof-right-index-title-no-stories">
                              
                            </strong>

                          <div class="prof-right-rating">
                              Rating: N/A
                          </div>

                          <strong class="review-body-index-right">
                            <%#= merchant.reviews.first.body %>
                            
                            Create story about <br>
                            <div class="button-writing-index-bg">
                              <span>
                               <%= link_to merchantright.name, merchant_url(merchantright) %>
                              </span>
                            </div>
                          </strong>
                        <% end %>
                          

                             

                      <% end %>

                          
                        
                     </div>
        </div>
    </div>

      <% end %>
      

app/views/merchants/edit.html.erb
<%= render "form", :merchant => @merchant %>

app/views/merchants/index.html.erb
<%# @merchants.sort_by { |cat| cat.categories }.each do |category| %>

<% @category.first(1).each do |category2| %>
      
  <%= render "merchants/content", :category => category2 %>
       
<% end %>



<script src="http://js.pusher.com/2.1/pusher.min.js"></script>

app/views/merchants/new.html.erb
	<%= render "form", :merchant => @merchant %>

app/views/merchants/search.html.erb
<div class="content-container">
  <% if (!@category.nil? || !@merchants.nil?) %>

    <ul style="list-style:none;">
    <% @merchants.each_with_index do |merchant, i| %>
      <% if merchant.photo.file? %>
          <%= image_tag merchant.photo.url(:big) %>
          <% else %>
            <%= image_tag "WGSlice/default-merchant.png", size: "120x120" %>
          <% end %>
      
          <br>
      <li>
        <a href="<%= merchant_url(merchant) %>">
        <span class="result-merchant-name"><%= merchant.name.upcase %></span>
        </a>
        <% if merchant.ranking(merchant) == nil %>
              <span style="font-weight:bold">Rank: Unranked</span>
            <% else %>
              <span style="font-weight:bold">Rank: <%= merchant.ranking(merchant) %> of <%= Merchant.all.count %></span>
            <% end %>
        <br>
        <!--on <%#= merchant.categories.first.name%> Online Store
        <br-->
        <%= merchant.country.name%>
        <br>
        Average Rating: <%= merchant.average_rating %>
        <br>
         based on <%= merchant.reviews.count %> <% if merchant.reviews.count > 1 %> stories
                                                <% else %> story
                                                <% end %>
        
      </li>



      <!--div class="search-write-story">
        <span>
          <% if current_user %>
              <%= link_to "Write a story!", new_merchant_review_url(merchant), style:"color:black;"%>
          <% end %>
        </span>
      </div-->
    <% end %>
    </ul>
    <%= paginate @merchants %>

  <% else %>
   <div class="noresult">
    <h1><%= "No results found!" %></h1>
    
    <%= link_to "Add a new online merchant", new_country_merchant_url(@country), class:"btn btn-wg"%>
   </div>
  <% end %>
</div>

app/views/merchants/show.html.erb
<div class="merchant-container">
  <div class="row">
    <div class="col-md-6">
        
        <div style="display:inline-block">
          <% if @merchant.photo.file? %>
            <%= image_tag @merchant.photo.url(:big), :class => "merchant-propic-profile", alt: @merchant.name %>
          <% else %>
              <%= image_tag "WGSlice/default-merchant.png", :class => "merchant-propic-profile", alt: @merchant.name %>            
          <% end %>
          <br>
          <span>
          Average Rating: <%= @merchant.average_rating %> 
            <br>

            (based on <%= @merchant.reviews.count %> stories)
            <br>
            
            <% if @merchant.ranking(@merchant) == nil %>
              Rank: Unranked
            <% else %>
              Rank: <%= @merchant.ranking(@merchant) %> of <%= Merchant.all.count %> online stores
            <% end %>
     
            <% if current_user %>
              <br>
              <%= button_to "Write a story!", new_merchant_review_url(@merchant), class:"btn btn-wg", method: :get%>
              <br><br>
            <% end %>
          </span>
        </div>

          

          
        <% if signed_in? %>
          <span class="attribute-container-merchant-show"> 
        <% else %>
          <span class="attribute-container-merchant-show-no-sign-in">
        <% end %>
            <span class = "user-username">
              <%= @merchant.name.upcase %>
              <br>          
            </span>     
             <strong class="following-number"> <%= @merchant.favorites.count %> </strong>
              <% if @merchant.favorites.count > 1 %> 
               <strong class="following-text"> Followers </strong>
              <% else %>
               <strong class="following-text"> Follower </strong>
              <% end %>  
              <% unless current_user == @user %>
              <span class="favs <%="is-favorite" if current_user.favorite_places.include?(@merchant)%>">
                <%= button_to "FOLLOW", merchant_favorites_url(@merchant),class:"btn btn-default", method: :post, form_class: "favorite-button grad_button", remote: true %>
                <%= button_to "UNFOLLOW", merchant_favorite_url(@merchant), class:"btn btn-warning", method: :delete, form_class: "unfavorite-button grad_button", remote: true %>
              </span>
            <% end %>
            <br><br><br><br><br><br>
          </span>
         
    </div>

    <div class="col-md-6">
      <%= image_tag "WGSlice/default-merchant-banner.png", class:"merchant-banner" %>
    </div>
  </div>
 

  <hr>
         
  <ul class="list-inline">
    <li><%= image_tag "WGSlice/default-merchant.png", class:"merchant-photo" %></li>
    <li><%= image_tag "WGSlice/default-merchant.png", class:"merchant-photo" %></li>
    <li><%= image_tag "WGSlice/default-merchant.png", class:"merchant-photo" %></li>
    <li><%= image_tag "WGSlice/default-merchant.png", class:"merchant-photo" %></li>
    <li><%= image_tag "WGSlice/more-shoppers-photo.png", class:"merchant-photo" %></li>
  </ul>
            
  <hr>

  <div class="row">
    <div class="col-md-2">
      <h4 class= "followed-merchants-text">
        Offers
      </h4>
    </div>
    <div class="col-md-10">
      <hr class="stripes">
    </div>
  </div>

   <div class = "row">
    <div class="col-md-6">
      <%= image_tag "WGSlice/dummy-merchant-offer.png", class:"offer-img"%>
      <p class="offer-text">
      Sapiente enim ut et consequatur reiciendis praesentium ipsam. Delectus nulla et consequuntur eum eos corporis et. Repudiandae earum omnis at odit consequatur quia. Ullam eum et veniam beatae. Qui nihil officiis qui nostrum veniam. Esse quod omnis sed sunt commodi ad. Cum rerum alias deserunt vitae iusto. Porro ut nemo incidunt id et. Suscipit et voluptas maiores. Eos cumque consequuntur dolores necessitatibus et. Quia iure accusantium quasi cumque distinctio dolores. Neque dolores labore impedit.
      </p>

    </div>

    <div class="col-md-6">
      <%= image_tag "WGSlice/dummy-merchant-offer.png", class:"offer-img"%>
      <p class="offer-text">
      Sapiente enim ut et consequatur reiciendis praesentium ipsam. Delectus nulla et consequuntur eum eos corporis et. Repudiandae earum omnis at odit consequatur quia. Ullam eum et veniam beatae. Qui nihil officiis qui nostrum veniam. Esse quod omnis sed sunt commodi ad. Cum rerum alias deserunt vitae iusto. Porro ut nemo incidunt id et. Suscipit et voluptas maiores. Eos cumque consequuntur dolores necessitatibus et. Quia iure accusantium quasi cumque distinctio dolores. Neque dolores labore impedit.
      </p>

    </div>
  </div>

            

  <div class="more-offers">
    <button class="btn btn-default btn-wg">More Offers</button>
  </div>    

  <hr>

  <div class="row">
    <div class="col-md-2">
      <h4 class= "followed-merchants-text">
        Stories
      </h4>
    </div>
    <div class="col-md-10">
      <hr class="stripes">
    </div>
  </div>

 
  <%= render "reviews/merchant_public", :merchant => @merchant %>
           
</div>


<script>

// NEW REVIEW MODAL

$(document).ready(function(){

  window.modal = {
    show: function(){
      $("body").addClass("has-active-modal");
    },
    hide: function(){
      $("body").removeClass("has-active-modal");
    }
  };

  $("body").on("click", ".show-modal", function(event){
    event.preventDefault();
    window.modal.show();
  });

  $(".modal").on("click", function(event){

    $target = $(event.target);

    if($target.is(".modal") || $target.is(".modal-close-button")){
      event.preventDefault();
      window.modal.hide();
    }
  });

  $("#jsform").on("ajax:send", function(event){
    $("#submit").attr('disabled', 'true');
  });

  $("#jsform").on("ajax:success", function(event, data){
    window.modal.hide();
    $(".reviews").prepend(data);
    $(".show-modal").remove();
  });

});

  // FAVORITES
  $('.favorite-button').on('ajax:send', function(event){
    $('.favs').toggleClass('is-favorite');
  });

  $('.unfavorite-button').on('ajax:send', function(event){
    $('.favs').toggleClass('is-favorite');
  });
</script>