config/routes.rb
WarmGreet::Application.routes.draw do

  get "guideline/index"

  get "about/index"

  get "electronics/index"

  get "writestory/write"

  get "profile/show"

  get "thankyou/index"

  get "sessions/new"

  get "merchants/index"

  get "reviews/story"

  get "favorites/show"

  get "follows/following"


  get "follows/followers"

  resources :users, :only => [:create, :new, :show, :edit, :update, :index, :profile] do
    resources :follows, :only => [:create, :destroy]
    get 'activate'
  end

  resources :categories, :only => [:create, :new, :show, :edit, :update, :index, :profile] do
    resources :follows, :only => [:create, :destroy]
    get 'activate'
  end

  


  resources :customers, :only => [:create, :new, :show, :edit, :update, :index] do
    #resources :follows, :only => [:create, :destroy]
    get 'activate'
  end

  resource :session, :only => [:create, :destroy, :new]

  resource :customersession, :only => [:create, :destroy, :new]

  resources :restaurants, :except => [:index, :new, :create] do
    resources :reviews, :only => [:create, :new, :index]
    resources :favorites, :only => [:create, :destroy]
  end

  resources :merchants, :except => [:index, :new, :create] do
    resources :reviews, :only => [:create, :new, :index]
    resources :favorites, :only => [:create, :destroy]
  end

  get 'search' => "merchants#search"

  #resources :cities, :only => [:show, :index] do
   # resources :restaurants, :only => [:index, :new, :create]
  #end

  resources :countries, :only => [:show, :index] do
    resources :merchants, :only => [:index, :new, :create]
  end

  resources :reviews, :only => [:show, :edit, :update, :destroy] do
    resources :vote_tags, :only => [:create, :destroy]
  end

  get '/auth/:provider/callback', to: 'sessions#create'

  root :to => "merchants#index"
  end

app/models/follow.rb
class Follow < ActiveRecord::Base
  attr_accessible :follower_id, :followed_id

  validates :follower_id, :followed_id, presence: true
  validates :follower_id, uniqueness: { scope: :followed_id, message: "You already followed this shopper!" }

  belongs_to :follower,
  class_name: "User",
  foreign_key: :follower_id,
  primary_key: :id

  belongs_to :followed,
  class_name: "User",
  foreign_key: :followed_id,
  primary_key: :id

end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController

  def create
    @user = User.find(params[:user_id])
    @follow = current_user.followed.new
    @follow.followed_id = @user.id
    @follow.save

    if request.xhr?
      headers["Content-Type"] = 'text/html; charset=utf-8'
      render "users/show"
    else
      redirect_to user_url(@follow.followed)
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @follow = current_user.followed.where("followed_id = ?", @user.id)
    @follow.first.destroy

    if request.xhr?
      headers["Content-Type"] = 'text/html; charset=utf-8'
      render "users/show"
    else
      redirect_to user_url(@follow.first.followed)
    end
  end

end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/views/follows/_follower_result.html.erb
<ul>
<%# user.followers.each do |follower| %>
  <li><%#= link_to follower.username, user_url(follower) %></li>
<%# end %>
</ul>

app/views/follows/_following_result.html.erb
<ul>
<% user.followed_users.each do |user| %>
  <li><%= link_to user.username, user_url(user) %></li>
<% end %>
</ul>

app/views/follows/_user.html.erb
<h3>Following</h3>
<%# @userf = user %>
<h3><%=user.followed_users.count%><%#= link_to user.followed_users.count, follows_following_url(user) %></h3>
<ul>
<% user.followed_users.each do |user| %>
  <li><%= link_to user.username, user_url(user) %></li>
<% end %>
</ul>


<h3>Followers</h3>
<h3><%=user.followers.count%><%#= link_to user.followers.count, follows_followers_url(user.followers) %></h3>
<ul>
<% user.followers.each do |follower| %>
  <li><%= link_to follower.username, user_url(follower) %></li>
<% end %>
</ul>

app/views/follows/followers.html.erb
<%= render "follower_result", :user => @user %>

app/views/follows/following.html.erb
<%= render "following_result", :user => @user %>