config/routes.rb
WarmGreet::Application.routes.draw do

  get "guideline/index"

  get "about/index"

  get "electronics/index"

  get "writestory/write"

  get "profile/show"

  get "thankyou/index"

  get "sessions/new"

  get "merchants/index"

  get "reviews/story"

  get "favorites/show"

  get "follows/following"


  get "follows/followers"

  resources :users, :only => [:create, :new, :show, :edit, :update, :index, :profile] do
    resources :follows, :only => [:create, :destroy]
    get 'activate'
  end

  resources :categories, :only => [:create, :new, :show, :edit, :update, :index, :profile] do
    resources :follows, :only => [:create, :destroy]
    get 'activate'
  end

  


  resources :customers, :only => [:create, :new, :show, :edit, :update, :index] do
    #resources :follows, :only => [:create, :destroy]
    get 'activate'
  end

  resource :session, :only => [:create, :destroy, :new]

  resource :customersession, :only => [:create, :destroy, :new]

  resources :restaurants, :except => [:index, :new, :create] do
    resources :reviews, :only => [:create, :new, :index]
    resources :favorites, :only => [:create, :destroy]
  end

  resources :merchants, :except => [:index, :new, :create] do
    resources :reviews, :only => [:create, :new, :index]
    resources :favorites, :only => [:create, :destroy]
  end

  get 'search' => "merchants#search"

  #resources :cities, :only => [:show, :index] do
   # resources :restaurants, :only => [:index, :new, :create]
  #end

  resources :countries, :only => [:show, :index] do
    resources :merchants, :only => [:index, :new, :create]
  end

  resources :reviews, :only => [:show, :edit, :update, :destroy] do
    resources :vote_tags, :only => [:create, :destroy]
  end

  get '/auth/:provider/callback', to: 'sessions#create'

  root :to => "merchants#index"
  end

app/controllers/customersessions_controller.rb
class CustomersessionsController < ApplicationController
end

app/helpers/customersessions_helper.rb
module CustomersessionsHelper
end

app/views/customersessions/new.html.erb
<form class="form-signin only" action="<%= session_url %>" method="post">

  <h2 class="form-signin-heading">Enter your credentials</h2>

  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <input class="form-control" id="user_username" name="user[username]" type="text" placeholder="Username" required autofocus>

  <br>
  
  <input class="form-control" id="user_merchant_number" name="user[merchant_number]" type="text" placeholder="Merchant Number" required>
  
  <br>
  
  <input class="form-control" id="user_password" name="user[password]" type="password" placeholder="Password" required>
  
  <br>
  <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>

  <div>
    <h5>No credentials yet? <%= link_to "Sign Up Now", new_customer_url %></h5>
  </div>
</form>